app/main_bp/models.py
from app import db

app/main_bp/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, FileField, SelectField, IntegerField, BooleanField)
from wtforms.validators import InputRequired, Length


class New_Guide(FlaskForm):
	subject            = StringField('Subject', validators=[InputRequired(),Length(min=10)], render_kw={"placeholder": 'for instance, How to change a Light Bulb'})
	description         = StringField('Description', validators=[InputRequired()])
	image               = FileField('Image')
	category = SelectField('Category')
	submit           = SubmitField('Submit')

app/main_bp/__init__.py
from flask import Blueprint

main_bp = Blueprint('main_bp', __name__, template_folder='templates', static_folder='static', static_url_path='/static/main')

from app.main_bp import routes

app/main_bp/routes.py
import flask
from app.main_bp import main_bp
from flask_login import current_user, login_required
from app import db
import app.main_bp.models as models
from app.main_bp.forms import New_Guide
# from app.utils import get_image, upload_image


@main_bp.route("/")
def index():
	white_pieces = ['rook', 'knight', 'bishop', 'queen', 'king', 'bishop', 'knight', 'rook']
	white_pawns = ['pawn'] * 8
	black_pieces = ['rook', 'knight', 'bishop', 'queen', 'king', 'bishop', 'knight', 'rook']
	black_pawns = ['pawn'] * 8

	return flask.render_template('index.html', white_pieces=white_pieces, white_pawns=white_pawns, black_pieces=black_pieces,
	                       black_pawns=black_pawns)

app/main_bp/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Chess Game</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('main_bp.static',filename='main/style/game.css')}}">
</head>
<body>
 <div class="container">
  <h1 class="text-center title">Chess Board</h1>
  <div class="chessboard">
      {% for row in range(8) %}
          {% for col in range(8) %}
              {% set position = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'][col] ~ (8 - row) %}
              <div id="{{ position }}" class="square {% if (row + col) % 2 == 0 %}white-square{% else %}black-square{% endif %}">
                  {% if col == 0 or col == 7%}
                      <div class="number-label">{{8 - row}}</div>
                  {% endif %}
                  {% if row == 0 %}
                      <div class="letter-label">{{ ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'][col] }}</div>
                      <img class="piece black {{ black_pieces[col] }}">
                  {% elif row == 1 %}
                      <img class="piece black {{ black_pawns[col] }}">
                  {% elif row == 6 %}
                      <img class="piece white {{ white_pawns[col] }}">
                  {% elif row == 7 %}
                      <div class="letter-label">{{ ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'][col] }}</div>
                      <img class="piece white {{ white_pieces[col] }}">
                  {% endif %}
              </div>
          {% endfor %}
      {% endfor %}
  </div>

  <div class="text-center mt-3">
      <button id="switchButton" class="btn btn-primary">Switch Pieces</button>
  </div>
</div>

    <script src="{{url_for('main_bp.static',filename='main/scripts/game.js')}}"></script>
</body>
</html>

app/main_bp/templates/partials/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fix Us</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('main_bp.static',filename='main/style.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/bf0597c63e.js" crossorigin="anonymous"></script>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    {% if style %}
    <link rel="stylesheet" href="{{url_for('main_bp.static',filename=style)}}">
    {% endif %}
  </head>
  <body>
{% include "partials/main/navbar.html" %}

  {% block content %}

  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

  <script src="{{url_for('main_bp.static',filename='main/scripts/base.js')}}"></script>

  </body>
</html>

app/main_bp/templates/partials/main/footer.html
 <footer class="bg-dark  ">
    <div class="container ">
      <div class="d-flex justify-content-center py-3">

        <div class="mb-4 mb-lg-0 footer-group py-3">
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="{{url_for('main_bp.about')}}" class=" text-uppercase text-white">About</a></li>
            <li class="mb-2"><a href="{{url_for('main_bp.contributions')}}" class="text-uppercase text-white">Credits & contributions</a></li>
            <li><small>Inspired by ifixit.com</small></li>
            
          </ul>
        </div>
        
        <div class="mb-lg-0 footer-group py-3">
          <h6 class="text-uppercase font-weight-bold mb-4">Social</h6>
          <p class="mb-4 text-white">Here you can find all my socials. <br> Would love to hear from you :)</p>
          <ul class="list-inline mt-4 ">
            <li class="list-inline-item"><a href="https://github.com/MiniManch" class='text-white' target="_blank" title="github"><i class="fa  fa-2x fa-github"></i></a></li>
            <li class="list-inline-item"><a href="https://www.instagram.com/emanuelrokah/" class='text-white' target="_blank" title="instagram"><i class="fab fa-2x fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="https://minimanch.github.io/" class='text-white' target="_blank" title="portfolio"><i class="fa-solid fa-2x fa-object-group"></i></a></li>
            <li class="list-inline-item"><a href="https://www.linkedin.com/in/emanuel-rokah-bb1a22158/" class='text-white' target="_blank" title="linkedin"><i class="fab fa-2x fa-linkedin"></i></a></li>
          </ul>
        </div>

      </div>
    </div>
  </footer>

app/main_bp/templates/partials/main/navbar.html
<div id='sidebar-container'>
      <i class="fa-solid fa-toolbox fa-2xl sidebar-drop-toggler" ></i>
  <div id='sidebar' class=" disabled d-flex flex-column flex-shrink-0 p-3 bg-light animate__animated">
      <i class="fa-solid fa-minimize sidebar-drop-toggler"  style="color: #000000;"></i>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="{{url_for('main_bp.index')}}" class="nav-link link-dark " aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          <i class="fa-solid fa-warehouse" style="color: #000000; margin-right: 1vh;"></i>
          Home
        </a>
      </li>
      <li class="nav-item">
        <a href="{{url_for('main_bp.guides')}}" class="nav-link link-dark " aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#guide-home"></use></svg>
          <i class="fa-solid fa-hammer" style="color: #000000; margin-right: 1vh;"></i>
          Guides
        </a>
      </li>
      <li>
        <a href="{{url_for('main_bp.tools')}}" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#tools"></use></svg>
          <i class="fa-solid fa-wrench" style="color: #000000; margin-right: 1vh;"></i>  
          Tools
        </a>
      </li>
      <li>
        <a href="{{url_for('main_bp.items')}}" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
          <i class="fa-solid fa-cart-shopping" style="color: #000000; margin-right: 1vh;"></i> 
          Store
        </a>
      </li>
    </ul>
    <hr>
    {% if current_user.is_authenticated%}
    <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="{{url_for('accounts_bp.profile')}}" class="nav-link link-dark " aria-current="page">
              <svg class="bi me-2" width="16" height="16"><use xlink:href="#profile"></use></svg>
              <i class="fa-solid fa-user" style="color: #000000; margin-right: 1vh;"></i> 
              Profile
            </a>
          </li>
          <li class="nav-item">
            <a href="{{url_for('accounts_bp.logout')}}" class="nav-link link-dark " aria-current="page">
              <svg class="bi me-2" width="16" height="16"><use xlink:href="#logout"></use></svg>
              <i class="fa-solid fa-arrow-right-from-bracket" style="color: #000000; margin-right: 1vh;"></i> 
              Log Out
            </a>
          </li>
          <li class="nav-item d-flex justify-content-start ms-3 mt-3">
            <img  src="https://res.cloudinary.com/drzcke4vu/image/upload/v1683294873/{{current_user.image}}" alt="user Image"
              class='rounded pb-5' style='max-width: 60px; display:inline-block;'> 
            <a href="#" class="nav-link link-dark mt-2 " aria-current="page">
              <strong>{{current_user.username}}</strong>
            </a>
            
          </li>
        </ul>

        {% else %}
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="{{url_for('accounts_bp.login')}}" class="nav-link link-dark " aria-current="page">
              <svg class="bi me-2" width="16" height="16"><use xlink:href="#login"></use></svg>
              <i class="fa-solid fa-arrow-right-to-bracket" style="color: #000000; margin-right: 1vh;"></i> 
              Log In
            </a>
          </li>
          <li class="nav-item">
            <a href="{{url_for('accounts_bp.signup')}}" class="nav-link link-dark " aria-current="page">
              <svg class="bi me-2" width="16" height="16"><use xlink:href="#signup"></use></svg>
              <i class="fa-solid fa-user-plus" style="color: #000000; margin-right: 1vh;"></i> 
              Sign Up
            </a>
          </li>
        </ul>
        {% endif %}
      {% if current_user.username == 'admin' %}

      <div class="btn-group dropend nav-link">
        <a type="button"  data-bs-toggle="dropdown" aria-expanded="false">
          Admin Links
        </a>
        <ul class="dropdown-menu">
          <li>
            <a class="nav-link" href="{{url_for('main_bp.tools_to_accept')}}">Tools to accept</a>
          </li>
          <li>
            <a class="nav-link" href="{{url_for('main_bp.guides_to_accept')}}">Guides to accept</a>
          </li>
        </ul>
      </div>
      {% endif %}

  </div>
</div>

{% with messages = get_flashed_messages() %}
  {% if messages %}
  {% for message in messages %}
      <div class=" alert message alert-warning alert-dismissible fade show" role="alert">
          {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
  {% endfor %}
  {% endif %}
{% endwith %}

