app/accounts_bp/models.py
from flask_login import UserMixin
from app import db
import time
import jwt

app/accounts_bp/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, PasswordField, EmailField, FileField)
from wtforms.validators import InputRequired, Email, Length, EqualTo
import email_validator


class ResetPasswordRequestForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(), Email()])
    submit = SubmitField('Request Password Reset')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[InputRequired()])
    confirm  = PasswordField('Confirm Password', validators=[InputRequired(), EqualTo('password')])
    submit = SubmitField('Change Password!')

app/accounts_bp/__init__.py
from flask import Blueprint

accounts_bp = Blueprint('accounts_bp', __name__, template_folder='templates', static_folder='static')

from app.accounts_bp import routes

app/accounts_bp/routes.py
import flask
from app.accounts_bp import accounts_bp, models
from app import db, mail,flask_app
import flask_mail
import os
import jwt
from .forms import ResetPasswordRequestForm, ResetPasswordForm
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
# from app.utils import get_image, upload_image


def send_email(subject, sender, recipients, html_body):
    msg = flask_mail.Message(subject, sender=sender, recipients=recipients)
    msg.html = html_body
    mail.send(msg)


def send_password_reset_email(user):
    token = user.get_reset_password_token(flask_app)
    send_email('Password reset',
               sender=os.environ['MAIL_APP_USERNAME'],
               recipients=[user.email],
               html_body=flask.render_template('email/reset_password.html', user=user, token=token))


@accounts_bp.route('/')
def accounts_index():
	return 'Hi from accounts'


@accounts_bp.route('/logout')
@login_required
def logout():
	logout_user()
	return flask.redirect(flask.url_for('main_bp.index'))


@accounts_bp.route('change_password/<int:user_id>', methods=['GET', 'POST'])
def change_password(user_id):
	user=models.User.query.filter_by(id=user_id).first()
	if user is None:
		flask.flash('An error has occurred')
		return flask.redirect(flask.url_for('main_bp.index'))

	form = ResetPasswordForm()
	if form.validate_on_submit():
		user.password = generate_password_hash(form.password.data, method='sha256')
		db.session.commit()
		flask.flash('Details were changed successfully')
		return flask.redirect(flask.url_for('accounts_bp.login'))

	return flask.render_template('change_password.html',form=form,title='Change Passowrd', style='accounts/new.css')


@accounts_bp.route('/reset_password_request', methods=['GET', 'POST'])
def reset_password_request():

    if current_user.is_authenticated:
        return flask.redirect(flask.url_for('main_bp.index'))

    form = ResetPasswordRequestForm()

    if form.validate_on_submit():
        user = models.User.query.filter_by(email=form.email.data).first()

        if user:
            send_password_reset_email(user)

        flask.flash('An email has been sent')
        return flask.redirect(flask.url_for('accounts_bp.login'))
    return flask.render_template('reset_password_request.html', style='accounts/new.css', title='Reset Password', form=form)

app/accounts_bp/templates/change_password.html
{% extends 'partials/accounts/base.html' %}
{% block content %}

<main id ='container-of-all' class="col-md-8 shadow bg-white rounded ">
    <form id="regForm" class='form' method="POST" action="#">
    <h1 class="title">{{title}}</h1>
        {{ form.hidden_tag()}}
        <div id="form-container" >
            <div>
            {{form.password(class='form-control guide-input',placeholder='Password')}}
            </div>
            <br>
            <div>
            {{form.confirm(class='form-control guide-input',placeholder='Confirm Password')}}
            </div>
            </div>
            <br>
            {{form.submit(class="button-paper")}}
        </div>
    </form>
</main>

{% endblock %}

app/accounts_bp/templates/login.html
{% extends 'partials/accounts/base.html' %}
{% block content %}

<main id ='container-of-all' class="col-md-8 shadow bg-white rounded ">
    <form id="regForm" class='form' method="POST" action="#">
    <h1 class="title">{{title}}</h1>
        {{ form.hidden_tag()}}
        <div id="form-container" >
            <div>
            {{form.email(class='form-control guide-input')}}
            </div>
            <br>
            <div>
            {{form.password(class='form-control guide-input',placeholder='Password')}}
            </div>
            <br>
            {{form.submit(class="button-paper")}}
        </div>
    </form>
    <a href="{{url_for('accounts_bp.reset_password_request')}}" class="button-paper">Forgot Password?</a>
</main>

{% endblock %}

app/accounts_bp/templates/partials/accounts/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fix Us</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('accounts_bp.static',filename='accounts/style.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/bf0597c63e.js" crossorigin="anonymous"></script>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    {% if style %}
    <link rel="stylesheet" href="{{url_for('accounts_bp.static',filename=style)}}">
    {% endif %}
  </head>
  <body>
{% include "partials/accounts/navbar.html" %}
    
  {% block content %}

  {% endblock %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

  <script src="{{url_for('main_bp.static',filename='main/scripts/base.js')}}"></script>


  </body>
</html>

app/accounts_bp/templates/partials/accounts/navbar.html
<div id='sidebar-container'>
      <i class="fa-solid fa-toolbox fa-2xl sidebar-drop-toggler" ></i>
  <div id='sidebar' class=" disabled d-flex flex-column flex-shrink-0 p-3 bg-light animate__animated">
      <i class="fa-solid fa-minimize sidebar-drop-toggler"  style="color: #000000;"></i>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="{{url_for('main_bp.index')}}" class="nav-link link-dark " aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          <i class="fa-solid fa-warehouse" style="color: #000000; margin-right: 1vh;"></i>
          Home
        </a>
      </li>
      <li class="nav-item">
        <a href="{{url_for('main_bp.guides')}}" class="nav-link link-dark " aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#guide-home"></use></svg>
          <i class="fa-solid fa-hammer" style="color: #000000; margin-right: 1vh;"></i>
          Guides
        </a>
      </li>
      <li>
        <a href="{{url_for('main_bp.tools')}}" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#tools"></use></svg>
          <i class="fa-solid fa-wrench" style="color: #000000; margin-right: 1vh;"></i>  
          Tools
        </a>
      </li>
      <li>
        <a href="{{url_for('main_bp.items')}}" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
          <i class="fa-solid fa-cart-shopping" style="color: #000000; margin-right: 1vh;"></i> 
          Store
        </a>
      </li>
    </ul>
    <hr>
    {% if current_user.is_authenticated%}
    <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="{{url_for('accounts_bp.profile')}}" class="nav-link link-dark " aria-current="page">
              <svg class="bi me-2" width="16" height="16"><use xlink:href="#profile"></use></svg>
              <i class="fa-solid fa-user" style="color: #000000; margin-right: 1vh;"></i> 
              Profile
            </a>
          </li>
          <li class="nav-item">
            <a href="{{url_for('accounts_bp.logout')}}" class="nav-link link-dark " aria-current="page">
              <svg class="bi me-2" width="16" height="16"><use xlink:href="#logout"></use></svg>
              <i class="fa-solid fa-arrow-right-from-bracket" style="color: #000000; margin-right: 1vh;"></i> 
              Log Out
            </a>
          </li>
          <li class="nav-item d-flex justify-content-start ms-3 mt-3">
            <img  src="https://res.cloudinary.com/drzcke4vu/image/upload/v1683294873/{{current_user.image}}" alt="user Image"
              class='rounded pb-5' style='max-width: 60px; display:inline-block;'> 
            <a href="#" class="nav-link link-dark mt-2 " aria-current="page">
              <strong>{{current_user.username}}</strong>
            </a>
            
          </li>
        </ul>

        {% else %}
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="{{url_for('accounts_bp.login')}}" class="nav-link link-dark " aria-current="page">
              <svg class="bi me-2" width="16" height="16"><use xlink:href="#login"></use></svg>
              <i class="fa-solid fa-arrow-right-to-bracket" style="color: #000000; margin-right: 1vh;"></i> 
              Log In
            </a>
          </li>
          <li class="nav-item">
            <a href="{{url_for('accounts_bp.signup')}}" class="nav-link link-dark " aria-current="page">
              <svg class="bi me-2" width="16" height="16"><use xlink:href="#signup"></use></svg>
              <i class="fa-solid fa-user-plus" style="color: #000000; margin-right: 1vh;"></i> 
              Sign Up
            </a>
          </li>
        </ul>
        {% endif %}
      {% if current_user.username == 'admin' %}

      <div class="btn-group dropend nav-link">
        <a type="button"  data-bs-toggle="dropdown" aria-expanded="false">
          Admin Links
        </a>
        <ul class="dropdown-menu">
          <li>
            <a class="nav-link" href="{{url_for('main_bp.tools_to_accept')}}">Tools to accept</a>
          </li>
          <li>
            <a class="nav-link" href="{{url_for('main_bp.guides_to_accept')}}">Guides to accept</a>
          </li>
        </ul>
      </div>
      {% endif %}

  </div>
</div>

{% with messages = get_flashed_messages() %}
  {% if messages %}
  {% for message in messages %}
      <div class=" alert message alert-warning alert-dismissible fade show" role="alert">
          {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
  {% endfor %}
  {% endif %}
{% endwith %}



app/accounts_bp/templates/profile.html
{% extends 'partials/accounts/base.html' %}
{% block content %}


<div class="row py-5 px-4" >
  <div class="col-md-5  cl-sm-12 mx-auto">
    <!-- Profile widget -->
    <div class="bg-white shadow rounded overflow-hidden p-3" id='user-container'>
      <div class="px-4 pt-0 pb-4 cover">
        <div class="media align-items-end profile-head " >
            {% if current_user.username == user.username %}
            <a href="{{url_for('accounts_bp.edit_profile',user_id=user.id)}}" class="btn btn-outline-dark btn-sm btn-block mt-3 edit-button ">Edit profile</a>
            {% endif %}

          <div class="profile mr-3 d-flex justify-content-start">
            <img src="https://res.cloudinary.com/drzcke4vu/image/upload/v1683294873/{{user.image}}" alt="..." width="130" class="rounded mb-2 mt-2 ">
            <h3 class=" mb-0 mt-5 ms-3">{{user.username}}</h3>
          </div>
        </div>
      </div>
      <div class="px-4 py-3">
        <h3 class="mb-0  ">ABOUT</h3>
        <div class="p-5 mt-3" id='about'>
          <p class="font-italic mb-0">{{current_user.about}}</p>
        </div>
      </div>
      <div class="py-4 px-4">
        <div class="d-flex align-items-center justify-content-between mb-3">
          <h3 class="mb-0">GUIDES</h3>
        </div>
        <div class="row">
            {% if user.guides|length == 0 and user.username == current_user.username %}
            <a href="{{url_for('main_bp.newguide')}}" class='button-paper' style='width:fit-content;'> Create a Guide!</a>
            {%endif%}
        {% for guide in user.guides %}
          <div class="col-lg-6 mb-2 pr-lg-1">
            <a class='user-guide-link-container' href="{{url_for('main_bp.guide',guide_id=guide.id)}}">
                <div class='g-fluid rounded shadow-sm user-guides-image' style='background-image: url("https://res.cloudinary.com/drzcke4vu/image/upload/v1683294873/{{guide.image}}") ;'>
                    <h4>{{guide.subject}}</h4>
                </div>
            </a>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}


app/accounts_bp/templates/reset_password_request.html
{% extends 'partials/accounts/base.html' %}
{% block content %}

<main id ='container-of-all' class="col-md-8 shadow bg-white rounded ">
    <form id="regForm" class='form' method="POST" action="#">
    <h1 class="title">{{title}}</h1>
        {{ form.hidden_tag()}}
        <div id="form-container" >
            <div>
            {{form.email(class='form-control guide-input',placeholder='Email address')}}
            </div>
            <br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
            </div>
            <br>
            {{form.submit(class="button-paper",style='margin-left:0; margin-top:3vh;')}}
        </div>
    </form>
</main>

{% endblock %}

app/accounts_bp/templates/signup.html
{% extends 'partials/accounts/base.html' %}
{% block content %}

<main id ='container-of-all' class="col-md-8 shadow bg-white rounded ">
    <form id="regForm" class='form' method="POST" action="#">
    <h1 class="title">{{title}}</h1>
        {{ form.hidden_tag()}}
        <div id="form-container" >
            <div>
            {{form.email(class='form-control guide-input')}}
            </div>
            <br>
            <div>
            {{form.password(class='form-control guide-input',placeholder='Password')}}
            </div>
            <br>
            {{form.password_confirm(class='form-control guide-input',placeholder='Confirm Password')}}
            <br>
            {{form.username(class='form-control guide-input',placeholder='Username')}}
            <br>
            <div>
            {{form.about(class='form-control guide-input',placeholder='Alittle about you!')}}
            </div>
            <br>
            {{form.submit(class="button-paper")}}
        </div>
    </form>
</main>

{% endblock %}